apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  # 사용할 ip address pool
  - 192.168.220.140-192.168.220.150
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  # 사용할 ip address pools, 여기선 'default' pool로 사용
  ipAddressPools:
  - default
